{% set name = "dash-ag-grid" %}
{% set version = "31.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_ag_grid-{{ version }}.tar.gz
  sha256: 71841499df8e302c5a22a403006045aa6ae3757648992d30bd5279d06eda5d0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dash >=2

test:
  imports:
    - dash_ag_grid

about:
  home: https://dash.plotly.com/dash-ag-grid
  summary: Dash wrapper around AG Grid, the best interactive data grid for the web.
  dev_url: https://github.com/plotly/dash-ag-grid
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohanMabille
