{% set name = "dash-ag-grid" %}
{% set version = "31.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_ag_grid-{{ version }}.tar.gz
  sha256: 8f609601d25225a53130d5a2da1f43c685dc640c777a7de80bbaa070ded3d19c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dash >=2
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_ag_grid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dash.plotly.com/dash-ag-grid
  summary: Dash wrapper around AG Grid, the best interactive data grid for the web.
  dev_url: https://github.com/plotly/dash-ag-grid
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - JohanMabille
