{% set name = "dash-ag-grid" %}
{% set version = "31.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_ag_grid-{{ version }}.tar.gz
  sha256: b346513a26b58e47422be9dfd56a053502a44636ca59b205ccbdaa76867facc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dash >=2
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_ag_grid
  commands:
    - pip check
#dash 2.18.2 has requirement Flask<3.1,>=1.0.4, but you have flask 3.1.0.
#dash 2.18.2 has requirement Werkzeug<3.1, but you have werkzeug 3.1.3
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://dash.plotly.com/dash-ag-grid
  summary: Dash wrapper around AG Grid, the best interactive data grid for the web.
  dev_url: https://github.com/plotly/dash-ag-grid
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - JohanMabille
